name: CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches:
     - '*'

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Repository checkout
      uses: actions/checkout@v2
    - name: Lint
      run: swiftlint
    - name: Build for macOS
      run: swift build -v
    - name: Run tests macOS
      run: swift test -v
    - name: Build for iOS
      run: set -o pipefail && env NSUnbufferedIO= YES xcodebuild build-for-testing -scheme Stargaze -destination "platform=iOS Simulator, OS=latest,name=iPhone 12" | xcpretty
    - name run iOS tests
      run: set -o pipefail && env NSUnbufferedIO= YES xcodebuild test-without-building -scheme Stargaze -destination "platform=iOS Simulator, OS=latest,name=iPhone 12" | xcpretty
