name: Stargaze CodeCoverage

on: [push]

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - name: Test
        uses: actions/checkout@v2
      - name: Build and Test
        run:  xcodebuild test -project Stargaze.xcodeproj -scheme Stargaze -destination 'platform=iOS Simulator,OS=latest,name=iPhone 12' -enableCodeCoverage YES build test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.2.1


